// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy0GMcaoETO0OCwZjix1mR9QcHBKdu5UA',
    appId: '1:1077155795487:web:8e3e67ade5b8450bca7b2a',
    messagingSenderId: '1077155795487',
    projectId: 'fir-task-6783f',
    authDomain: 'fir-task-6783f.firebaseapp.com',
    storageBucket: 'fir-task-6783f.appspot.com',
    measurementId: 'G-HHS6KD7NW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABpI7RheO4Wf1ZEooSqMfM0HnYqPFkeEo',
    appId: '1:1077155795487:android:8c6aae6495aea1cbca7b2a',
    messagingSenderId: '1077155795487',
    projectId: 'fir-task-6783f',
    storageBucket: 'fir-task-6783f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYY_BKywI2wqrwU1ULt3TgvX2peY0aq74',
    appId: '1:1077155795487:ios:f2cd0af26db7dc63ca7b2a',
    messagingSenderId: '1077155795487',
    projectId: 'fir-task-6783f',
    storageBucket: 'fir-task-6783f.appspot.com',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYY_BKywI2wqrwU1ULt3TgvX2peY0aq74',
    appId: '1:1077155795487:ios:5b2b31e89fc2c7f2ca7b2a',
    messagingSenderId: '1077155795487',
    projectId: 'fir-task-6783f',
    storageBucket: 'fir-task-6783f.appspot.com',
    iosBundleId: 'com.example.firebasetask.RunnerTests',
  );
}
